name: nutri_mind_application
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0
  animated_splash_screen: ^1.3.0
  page_transition: ^2.0.9
  google_fonts: ^5.1.0
  http: ^1.1.0
  flutter_verification_code: ^1.1.6
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  numberpicker: ^2.1.2
  syncfusion_flutter_gauges: ^22.2.12
  agora_rtc_engine: ^6.2.2
  permission_handler: ^10.4.5
  dio: ^5.3.2
  shared_preferences: ^2.2.1
  conditional_builder_null_safety: ^0.0.6
  flutter_rating_bar: ^4.0.1
  card_swiper: ^3.0.1
  url_launcher: ^6.1.14
  custom_clippers: ^2.0.0
  font_awesome_flutter: ^10.5.0
  syncfusion_flutter_sliders: ^22.2.12
  dropdown_button2: ^2.3.9
  #flutter_offline: ^3.0.0
  connectivity_plus: ^4.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.3

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
    - family: RacingSansOne
      fonts:
        - asset: assets/fonts/RacingSansOne-Regular.ttf
